services:
  embedder:
    build: ./embedder
    volumes:
    - ./embedder/known_faces:/app/known_faces
    - ./crawler/crawled_faces:/app/crawled_faces:ro
    environment:
    - QDRANT_HOST=qdrant
    - QDRANT_PORT=6333
    - QDRANT_API_KEY=qdrantapikey
    depends_on:
    - qdrant
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [ gpu ]

  lookup:
    build: ./lookup
    ports:
    - "5000:5000"
    volumes:
    - ./embedder/known_faces:/app/known_faces:ro
    - ./crawler/crawled_faces:/app/crawled_faces:ro
    environment:
    - QDRANT_HOST=qdrant
    - QDRANT_PORT=6333
    depends_on:
    - embedder
    - qdrant
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [ gpu ]

  crawler:
    build: ./crawler
    volumes:
    - ./crawler/crawled_faces:/app/crawled_faces
    environment:
    - START_URL=https://www.southpole.com/about-us/our-leadership-team
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [ gpu ]

  video:
    build: ./video
    volumes:
    - ./crawler/crawled_faces:/app/crawled_faces:ro
    - ./crawler/transcriptions:/app/transcriptions
    environment:
    - MINIO_ENDPOINT=minio:9000
    - MINIO_USER=${MINIO_USER}
    - MINIO_PASSWORD=${MINIO_PASSWORD}
    depends_on:
    - minio
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [ gpu ]

  minio:
    image: minio/minio
    container_name: minio
    ports:
    - "9000:9000"
    - "9001:9001"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
    - MINIO_ROOT_USER=miniouser
    - MINIO_ROOT_PASSWORD=miniopassword
    command: server /data --console-address ":9001"
    volumes:
    - minio_data:/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    environment:
    - QDRANT__SERVICE__API_KEY=qdrantapikey
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
    - 6333:6333
    - 6334:6334
    volumes:
    - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
  minio_data:
